
springdoc:
  api-docs:
    path: /creditcard/payment-api-docs

  swagger-ui:
    filter: true
    path: /creditcard/payment-documentation
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG
    com.reservation.hotel.feign: DEBUG  # Your package
    org.springframework.cloud.openfeign: DEBUG
#services:
#  creditcard:
#    name: credit-card-payment-service
#    base-url: http://localhost:9091/host/credit-card-payment-api
#
